### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by samlipworth** [nluhmann/BlastFrost#1]
Hi!

I followed the compilation instructions but get the following error when trying to execute BlastFrost - do you know what is going wrong? Looks like it compiled ok - didn't get any warnings..

./BlastFrost: error while loading shared libraries: libbifrost.so: cannot open shared object file: No such file or directory

**Comment by nluhmann** [comment]
Hi!
Thanks for testing my installation instructions and sorry they were incomplete. As BlastFrost relies on the Bifrost API, you need to install that library first: https://github.com/pmelsted/bifrost
After BlastFrost should be able to find the shared library. Hope that works!

**Comment by samlipworth** [comment]
Ooops yes thanks should have spotted that - well an easy fix for BlastFrosts first issue - thanks!
